name: Docs ðŸ“š

on:
  push: { branches: [ main ] }

jobs:
  updateDescriptions:
    name: "ðŸ“š Update ${{ matrix.imageType }} description on dockerhub"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        imageType:
          - base
          - hub
          - editor
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Caveat - Currently we use the ubuntu readme as we do not have a catch-all readme (yet?)
      - run: |
          echo "SHORT_DESCRIPTION=$(cat ./images/ubuntu/${{ matrix.imageType }}/100-characters-dockerhub-description.txt)" >> $GITHUB_ENV
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LEGACY_PASSWORD }}
          repository: unityci/${{ matrix.imageType }}
          short-description: ${{ env.SHORT_DESCRIPTION }}
          readme-filepath: ./images/ubuntu/${{ matrix.imageType }}/README.md
