name: New Base Version â›­

on:
  repository_dispatch:
    types: [new_base_image_requested]

# Further reading:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch
# https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-repository-dispatch-event
# https://developer.github.com/webhooks/event-payloads/#repository_dispatch

jobs:
  build:
    name: "ðŸ›  Build unityci/base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      ###########################
      #        Variables        #
      ###########################
      - name: Show hook input
        run: |
          echo "Event ${{ github.event.event_type }}"
          echo "Payload ${{ github.event.client_payload }}"
          echo "Image tag (patch): ${{ github.event.client_payload.patchTag }}"
          echo "Image tag (minor): ${{ github.event.client_payload.minorTag }}"
          echo "Image tag (major): ${{ github.event.client_payload.majorTag }}"
      ###########################
      #          Setup          #
      ###########################
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check if image not already exists
        run: |
          # Source: https://stackoverflow.com/a/39731444/3593896
          function docker_tag_exists() {
            curl --silent -f -lSL https://index.docker.io/v1/repositories/$1/tags/$2 > /dev/null
          }

          if docker_tag_exists unityci/base ubuntu-${{ github.event.client_payload.patchTag }} ; then
            echo "Image already exists. Exiting."
            exit 1
          fi
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base
            ${{ runner.os }}-buildx-

      ###########################
      #        Base image       #
      ###########################
      - name: Build and publish
        uses: docker/build-push-action@v2
        id: build_base_image
        with:
          context: .
          file: ./base/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            unityci/base:ubuntu-${{ github.event.client_payload.patchTag }}
            unityci/base:${{ github.event.client_payload.patchTag }}
            unityci/base:ubuntu-${{ github.event.client_payload.minorTag }}
            unityci/base:${{ github.event.client_payload.minorTag }}
            unityci/base:ubuntu-${{ github.event.client_payload.majorTag }}
            unityci/base:${{ github.event.client_payload.majorTag }}
            unityci/base:ubuntu-latest
            unityci/base:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect unityci/base:ubuntu-${{ github.event.client_payload.patchTag }}
      - name: Image digest
        run: echo ${{ steps.build_base_image.outputs.digest }}
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: unityci/base
          short-description: $(cat ./base/100-characters-dockerhub-description.txt)
          readme-filepath: ./base/README.md
